export interface IBook {
    id?: number,
    name: string,
    image?: string,
    publicationYear: number,
    description: string,
    price: number,
    quantity: number,
    languagesID: number[],
    authorsID: number[],
    genresID: number[],
    isbn?: number,
    formatsID: number[],
    rating: string,
    coverImageLink: string,
}

export interface IBookGet {
    id?: number,
    name: string,
    image?: string,
    publicationYear: number,
    description: string,
    price: number,
    quantity: number,
    languages: string & number[],
    authors: string & number[],
    genres: string & number[],
    isbn?: number,
    formats: string & number[],
    rating: string,
    coverImageLink: string,
}